language: c
 
install:
  - echo 'yes' | sudo add-apt-repository ppa:directhex/monoxide
  - sudo apt-get update
  - sudo apt-get install mono nunit
 
script:
  - xbuild CI.proj
  - nunit-console ./Test/PagarMe.Tests/bin/Debug_Net40/PagarMe.Tests.dll -exclude NotWorkingOnMono
